Repository woorifisa-service-dev/backend-2nd-LatePass, pull requests merged in 2023-07, with the labels that each got.

#8 Member Entity 생성
  backend/src/main/java/dev/chrono/chronochallenge/model/Member.java
Labels: enhancement

#10 feat: Quiz Entity 추가
  backend/src/main/java/dev/chrono/chronochallenge/model/Quiz.java
Labels: enhancement

#14 feat: member repository, service, controller 생성
  .gitignore
  backend/src/main/java/dev/chrono/chronochallenge/controller/MemeberController.java
  backend/src/main/java/dev/chrono/chronochallenge/controller/SampleController.java
  backend/src/main/java/dev/chrono/chronochallenge/repository/MemberRepository.java
  backend/src/main/java/dev/chrono/chronochallenge/repository/SampleRespository.java
  backend/src/main/java/dev/chrono/chronochallenge/service/CrudSevice.java
  backend/src/main/java/dev/chrono/chronochallenge/service/MemberService.java
  backend/src/main/java/dev/chrono/chronochallenge/service/MemberServiceImpl.java
  backend/src/main/java/dev/chrono/chronochallenge/service/SampleService.java
Labels: enhancement

#13 refactor: Member Entity 수정
  backend/src/main/java/dev/chrono/chronochallenge/model/Member.java
Labels: refactor

#17 refactor: Quiz Entity 수정, SampleModel삭제
  backend/src/main/java/dev/chrono/chronochallenge/model/Quiz.java
  backend/src/main/java/dev/chrono/chronochallenge/model/SampleModel.java
Labels: refactor

#15 feat: member 정보 조회 api 구현
  backend/src/main/java/dev/chrono/chronochallenge/controller/MemeberController.java
  backend/src/main/java/dev/chrono/chronochallenge/dto/SampleDto.java
  backend/src/main/java/dev/chrono/chronochallenge/dto/response/MemberResponse.java
Labels: 기능 추가, 백엔드

#21 refactor: 기능별 mvc구조로 변경
  backend/src/main/java/dev/chrono/chronochallenge/member/controller/MemeberController.java
  backend/src/main/java/dev/chrono/chronochallenge/member/dto/response/MemberResponse.java
  backend/src/main/java/dev/chrono/chronochallenge/member/model/Member.java
  backend/src/main/java/dev/chrono/chronochallenge/member/repository/MemberRepository.java
  backend/src/main/java/dev/chrono/chronochallenge/member/service/CrudSevice.java
  backend/src/main/java/dev/chrono/chronochallenge/member/service/MemberService.java
  backend/src/main/java/dev/chrono/chronochallenge/member/service/MemberServiceImpl.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/model/Quiz.java
  backend/src/main/java/dev/chrono/chronochallenge/service/MemberService.java
Labels: 리팩토링

#23 Refactor/modify project structure
  backend/src/main/java/dev/chrono/chronochallenge/common/service/CrudSevice.java
  backend/src/main/java/dev/chrono/chronochallenge/member/service/MemberService.java
Labels: 리팩토링, 백엔드

#26 fix: member controller 의존성 관련 오류 수정
  backend/src/main/java/dev/chrono/chronochallenge/member/controller/MemeberController.java
  backend/src/main/java/dev/chrono/chronochallenge/member/dto/response/MemberResponse.java
  backend/src/main/java/dev/chrono/chronochallenge/member/service/MemberServiceImpl.java
Labels: bug

#27 feat: quiz API 구현
  backend/src/main/java/dev/chrono/chronochallenge/common/service/CrudService.java
  backend/src/main/java/dev/chrono/chronochallenge/member/service/MemberService.java
  backend/src/main/java/dev/chrono/chronochallenge/member/service/MemberServiceImpl.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/controller/QuizController.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/dto/response/QuizResponse.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/dto/rquest/QuizRequest.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/model/Quiz.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/repository/QuizRepository.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/service/QuizService.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/service/QuizServiceImpl.java
Labels: 기능 추가, 백엔드

#29 Feat: Swagger 구현
  backend/build.gradle
  backend/src/main/java/dev/chrono/chronochallenge/config/SwaggerConfig.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/controller/QuizController.java
Labels: 기능 추가, 백엔드

#30 feat: 로그인 로그아웃 Api 구현
  backend/src/main/java/dev/chrono/chronochallenge/auth/controller/AuthController.java
  backend/src/main/java/dev/chrono/chronochallenge/auth/dto/AuthInfo.java
  backend/src/main/java/dev/chrono/chronochallenge/auth/dto/request/LoginRequest.java
  backend/src/main/java/dev/chrono/chronochallenge/auth/exception/LoginFailedException.java
  backend/src/main/java/dev/chrono/chronochallenge/auth/service/AuthService.java
  backend/src/main/java/dev/chrono/chronochallenge/config/WebConfig.java
  backend/src/main/java/dev/chrono/chronochallenge/member/repository/MemberRepository.java
Labels: 기능 추가

#35 refactor : Quiz Entity 필드 타입 수정 및 연관 파일 자료형 수정
  backend/src/main/java/dev/chrono/chronochallenge/quiz/dto/response/QuizResponse.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/dto/rquest/QuizRequest.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/model/Quiz.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/model/QuizStatus.java
Labels: 리팩토링

#36 feat: 로그인 조회 API 구현
  backend/src/main/java/dev/chrono/chronochallenge/auth/controller/AuthController.java
  backend/src/main/java/dev/chrono/chronochallenge/auth/dto/MessageResponse.java
  backend/src/main/java/dev/chrono/chronochallenge/auth/service/AuthService.java
Labels: 기능 추가, 백엔드

#37 feature : 활성화된 퀴즈만 조회하는 api 추가
  backend/src/main/java/dev/chrono/chronochallenge/quiz/controller/QuizController.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/repository/QuizRepository.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/service/QuizService.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/service/QuizServiceImpl.java
Labels: 기능 추가

#38 feature/31 grade a quiz
  backend/.gitignore
  backend/src/main/java/dev/chrono/chronochallenge/auth/controller/AuthController.java
  backend/src/main/java/dev/chrono/chronochallenge/auth/service/AuthService.java
  backend/src/main/java/dev/chrono/chronochallenge/common/dto/MessageResponse.java
  backend/src/main/java/dev/chrono/chronochallenge/config/WebConfig.java
  backend/src/main/java/dev/chrono/chronochallenge/member/model/Member.java
  backend/src/main/java/dev/chrono/chronochallenge/member/service/MemberService.java
  backend/src/main/java/dev/chrono/chronochallenge/member/service/MemberServiceImpl.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/controller/ProblemController.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/dto/rquest/AnswerRequest.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/model/Quiz.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/service/ProblemService.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/service/QuizService.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/service/QuizServiceImpl.java
  backend/src/main/resources/application.properties
Labels: 기능 추가, 백엔드

#42 fix: QuizService 수정
  backend/src/main/java/dev/chrono/chronochallenge/quiz/service/QuizService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
Labels: 버그 발생!, 백엔드

#40 feature : Quiz Entity 내 생성, 수정일자 받아오는 기능 추가
  backend/src/main/java/dev/chrono/chronochallenge/ChronoChallengeApplication.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/model/Quiz.java
Labels: 기능 추가

#44 refactor: 문제 채점 API 퀴즈 정답 확인에 대한 로직 수정
  backend/src/main/java/dev/chrono/chronochallenge/quiz/controller/ProblemController.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/service/ProblemService.java
Labels: 리팩토링, 백엔드

#46 feat: 전체 ui 구현
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/HelloWorld.vue
  frontend/src/components/Modal.vue
  frontend/src/components/QuizCard.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/Default.vue
  frontend/src/layouts/default/View.vue
  frontend/src/main.js
  frontend/src/plugins/vuetify.js
  frontend/src/router/index.js
  frontend/src/store/app.js
  frontend/src/store/index.js
  frontend/src/store/useUserStore.js
  frontend/src/views/Admin.vue
  frontend/src/views/CreateAndEditQuiz.vue
  frontend/src/views/Home.vue
  frontend/src/views/Login.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/Quiz.vue
  frontend/src/views/QuizList.vue
  frontend/yarn.lock
Labels: 프론트엔드, UI

#49 feat: 지난 문제 보러가기 페이지 API 연동
  backend/src/main/resources/application.properties
  frontend/src/views/QuizList.vue
Labels: 기능 추가, 프론트엔드

#50 feature: 퀴즈 상태값이 활성화된 부분만 퀴즈 풀기 페이지에 보여주는 로직 구현
  .gitignore
  backend/src/main/java/dev/chrono/chronochallenge/quiz/dto/response/QuizResponse.java
  backend/src/main/resources/application.properties
  frontend/src/views/Quiz.vue
Labels: 기능 추가, 프론트엔드

#52 feat: 마이페이지와 어드민 페이지에 기능을 추가했다
  backend/src/main/java/dev/chrono/chronochallenge/auth/dto/request/LoginRequest.java
  backend/src/main/java/dev/chrono/chronochallenge/member/model/Member.java
  backend/src/main/java/dev/chrono/chronochallenge/quiz/dto/response/QuizResponse.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/layouts/default/AppBar.vue
  frontend/src/store/useUserStore.js
  frontend/src/views/Admin.vue
  frontend/src/views/CreateAndEditQuiz.vue
  frontend/src/views/MyPage.vue
  frontend/yarn.lock
Labels: 기능 추가, 프론트엔드

#53 docs: 퀴즈 풀기 게임에 대한 docs 작성
  README.md
Labels: documentation

#56 fix: router view 이름 오타 수정
  frontend/src/router/index.js
Labels: 버그 발생!

#58 chore: package.json preview 실행문 수정
  frontend/package.json
Labels: chore

#60 refactor: backend api url 변경
  frontend/src/consts/index.js
Labels: 리팩토링

#62 refactor: CORS 허용 URL 수정
  backend/src/main/java/dev/chrono/chronochallenge/config/WebConfig.java
Labels: 리팩토링, 백엔드

#64 refactor: 주요정보 변수 처리
  backend/src/main/resources/application.properties
Labels: 리팩토링, 백엔드

#68 refactor: cors origin url 로컬 주소 추가
  backend/src/main/java/dev/chrono/chronochallenge/config/WebConfig.java
Labels: 리팩토링
